# Generated by Django 2.2.7 on 2020-08-28 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(null=True, through='proyecto.User_Project', to=settings.AUTH_USER_MODEL),
        ),
    ]
