# Generated by Django 2.2.7 on 2020-08-29 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20200828_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users', through='proyecto.User_Project', to=settings.AUTH_USER_MODEL),
        ),
    ]
