# Generated by Django 2.2.7 on 2020-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requeriments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rf',
            name='specific',
            field=models.BooleanField(default=False),
        ),
    ]
