# Generated by Django 2.2.7 on 2020-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requeriments', '0002_rf_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnf',
            name='specific',
            field=models.BooleanField(default=False),
        ),
    ]
